POST http://localhost:8081/users
Content-Type: application/json

{
  "email": "test121@example.com",
  "name": "홍길동",
  "mobile": 1234,
  "addresses": [
    {
      "type": "Home",
      "zipcode": "1234"
    }
  ]
}

###

DELETE http://localhost:8081/users/1
Content-Type: application/json


###
PUT http://localhost:8081/users/1
Content-Type: application/json

{
  "account": "test121@example.com",
  "name": "홍길동",
  "mobile": 1234,
  "addresses": [
    {
      "type": "Home",
      "zipcode": "1234"
    }
  ]
}


###
PATCH http://localhost:8081/users/1
Content-Type: application/json

{
  "email": "test12@example.com",
  "name": "홍길동",
  "mobile": 1234,
  "addresses": [
    {
      "type": "Home",
      "zipcode": "1234"
    }
  ]
}